# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

pod 'simdjson', path: '../node_modules/@nozbe/simdjson'
target 'CommEazyTemp' do
  config = use_native_modules!

  # Enable modular headers for Firebase and its dependencies (required by Swift pods)
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseAuth', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'GTMSessionFetcher', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'nanopb', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'CommEazyTempTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Configure sherpa-onnx framework and headers for PiperTtsModule
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Fix deployment target warnings - set minimum to 15.1
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

        # Add header search path for sherpa-onnx C API
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/../Frameworks/sherpa-onnx-include"'

        # Enable C++20 (required by React Native 0.76+, also compatible with sherpa-onnx)
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'

      end
    end

    # Patch fmt header: disable consteval for Apple Clang 17+ (Xcode 26)
    # fmtlib 11.0.2 only guards against Apple Clang < 14, but Xcode 26 (Clang 17) also has consteval bugs
    fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      # Extend the Apple Clang guard to cover version 17+ as well
      old_guard = '#elif defined(__apple_build_version__) && __apple_build_version__ < 14000029L'
      new_guard = '#elif defined(__apple_build_version__)'
      if content.include?(old_guard)
        content.gsub!(old_guard, new_guard)
        File.write(fmt_base, content)
        Pod::UI.puts "[fmt] Patched base.h: disabled consteval for all Apple Clang versions"
      end
    end
  end
end
